// segmented_code.c
// Generated by decompiling segmented.bin
// using Reko decompiler version 0.9.4.0.

#include "segmented.h"

// 1000:0020: void entry()
void entry()
{
	// SystemError: Object reference not set to an instance of an object.
	// AttributeError: Unknown event: 'undefined_event'
	// RecursionError: maximum recursion depth exceeded
	// KeyError: 1000:0010
}

